### ISSUE TITLE
mongodb answers表内自动生成大量垃圾数据

### ISSUE THREAD

**Issue by qianghuang84** [LiangCY/questionnaire#3]
你好！非常谢谢你开源这个问卷系统。在使用过程中发现在mongodb上的表answers会生成大量的垃圾数据，不知为何这样，暂时还没找到原因。上传数据如下。

[answers.zip](https://github.com/LiangCY/questionnaire/files/923332/answers.zip)

**Comment by LiangCY** [comment]
看数据应该是有人尝试在前端进行了SQL注入、XSS等攻击，产生了大量错误数据。
出现这个问题的原因是因为后台没有对前端提交的数据进行校验，前端提交问卷时提交的数据为问卷id和转成JSON字符串的问题的答案（JSON字符串为“问题：答案”的形式），因为没有做校验，所以后台其实是可以接受任意形式的字符串的。
我当时只是用这个项目练习一下React的，所以并没有考虑太多……
解决的办法是在answer的controller里，对提交答案的接口做一下内容的校验，用JSON.parse和try-catch应该已经可以避免大部分的攻击。

**Comment by qianghuang84** [comment]
谢谢你的解决方案，也祝你的项目越来越成功。
